version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5001:5000
      env_file:
      - .flaskenv
    depends_on:
      - db

  db:
    image: postgres:13.4-alpine
    environment:
      - POSTGRES_USER=your_username
      - POSTGRES_PASSWORD=your_password
      - POSTGRES_DB=your_database
